language: ruby
cache: bundler
rvm:
- 2.2
matrix:
  include:
  - rvm: 2.2
  fast_finish: true
script: bundle exec jekyll build
deploy:
  provider: script
  script: "./script/deploy.sh"
  skip_cleanup: true
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
