language: ruby
cache: bundler
rvm:
- 2.1
matrix:
    include:
        - rvm: 2.2
    fast_finish: true

script: bundle exec jekyll build

before_deploy:
  - chmod +x deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
        # - secure: 3a712a9ca3116172be1200bfdac52ff5499f489f
