language: ruby
cache: bundler
rvm:
- 2.2
matrix:
  include:
  - rvm: 2.2
  fast_finish: true
script: bundle exec jekyll build
deploy:
  provider: script
  script: "./script/deploy.sh"
  skip_cleanup: true
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: lgjJfbw2UQ827a1NrOJ2/GiC6XZVA0/p44ENGM8P2NiaBJipuPKYEu84Zx6TN3ATE98n9S42MB1Q6NQhfcSsHdoPGi2u91zqVK4yn+4FfxUqU75kUD8WO2KdZSYIRrXjKRwNZ8RsTv4amg5d1D+0qky89U4/ezm8rdqsPTO16YMpkBVLthCN98nrx70oWGTwL6hWv1jYUlZxXGSLo5aisTEYhDgahEL02ZAQJlD8U3o6GO9N+LFdEAkAYDKF6qUV6RrBbVmvRi+L8kaOOs7+Rc1EQIWgyCHYuibdiD57nXxzzG2jKKH0W/Ee7t2/m42dPWbgpwaQGnZLBeVnJTEwCe4VQXottKhpEZeyjTgufktXNxHQz7Txoq7yMo1Ie1qcrqnOs8TuHTRNUXMr+IwNKwPKixdSpXUyZ43TfbAp0f6cpRCCTUbh3ybnyJ8tc8pCiZRVTFMs55+lWjrsX/OTrN6QW0FK/A7Txlz+R92SLuwqhzX1h4Gw7shPv78tozE1Pmd9bKuriHEpedeU9LqQcVZvvvufg/sGXJAFvGFhtU1BKMyZCBBD3Npy4ydUafo88VecxaqxP4aVVxBUCcbGIHyztXnXvaDQH3n6fLC/Teh+P0X+71Aw8n8ex/o44WUhi4zGy6gLaKpvueJV4l1R7r9FOrXg7y+yZZLpsNJ2YM0=
