# Site settings
title: bertrandkeller
email: bertrand.keller@gmail.com
description: Découvrir des choses et d'autres

baseurl: ""
permalink: /:year/:month/:day/:title
url: "http://bertrandkeller.info"
github_username:  bertrandkeller
# gems:
#   - jekyll-assets

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

sass:
  sass_dir: _sass
  style: compressed

text:
  pagination:
    newer: 'Précédent'
    older: 'Suivant'

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE
  - README.md
  - notes-integration.md
  - script

# Plugin: jekyll-assets

# assets:
#   sources:
#     - assets/js
#     - assets/css
#     - _sass
#   autoprefixer:
#     browsers: ["last 2 versions","> 5%","IE 9"]
