# Site informations
name: 'Bertrand Keller'
title: bertrandkeller
email: bertrand.keller@gmail.com
description: Découvrir des choses et d'autres
subject: Histoire de gestion de contenu, générateur de site statique et autres

# Site settings
baseurl: ""
permalink: /:year/:month/:day/:title/
url: "https://bertrandkeller.info"
lang: fr
timezone: Europe/Paris
mainColor: '#000000'
incremental: true
profile: true
encoding: utf-8
 

 # seo-tag
author: Bertrand Keller
logo: /assets/bertrandkeller.png
image:
  path: /assets/bertrandkeller.png
  height: 200
  width: 200
twitter:
  username: bertrandkeller
social:
  type: personn
  name: Bertrand Keller
  links:
    - https://twitter.com/bertrandkeller
    - https://github.com/bertrandkeller

# Build settings
markdown: kramdown
kramdown:
  input: GFM

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      publisher: Bertrand Keller

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

sass:
  sass_dir: _sass
  style: compressed

feed:
  path: feed

text:
  pagination:
    newer: 'Précédent'
    older: 'Suivant'

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-assets
  - octopress-autoprefixer
  - jekyll-include-cache
  - jekyll-tidy

include:
  - _redirects
  - _headers
  
exclude:
  - .cache
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ruby-version
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - script
  - vendor
  - gems
  - tmp
  - LICENSE.md
  - README.md
  - dploy.yml
  - LICENSE

jekyll_tidy:
  compress_html: true
  exclude: ["sw.js","404.html","offline.md"]

Plugin: jekyll-assets
assets:
  sources:
    - assets/js
    - assets/css
    - _sass
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
